#!/usr/bin/env bash
# This script displays Best School 10 times, and Hi on the 9th

x=1

while [ $x != 9 ] && [ $x -le 10 ]
do 
	echo "Best School"
	x=$((x + 1))

	if [ $x = 9 ]
		then echo "Best School"
		echo "Hi"
		x=$((x + 1))
	fi
done
