#!/usr/bin/env bash
# This script displays bad luck on fourth, good lick on 8th, and Best School for all other iterations

x=0

while  [ $x -lt 10 ]
do 
	x=$((x + 1))
	
	if [ $x = 4 ]
	then
		echo "bad luck"
	elif [ $x = 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	
done
