#!/usr/bin/env bash
# This script displays info on the school file

X=school

if [ -e $X ]
then echo "school file exists"

	if [ -s $X ]
	then echo "school file is empty"

	else echo "school file is not empty"
	fi

	if [ -f $X ]
	then echo "school is a regular file"
	fi

else echo "school file does not exist"
fi

