#!/usr/bin/env bash
#This script creates a file, and runs a script that prints To infinity and beyond, unless it receives a SIG

F=/var/run/myscript.pid
D=manage_my_process

if [ "$1" = start ]
then
        ./$D &
        echo "echo $!" > $F
        echo "manage_my_process started"

elif [ "$1" = stop ]
then
        sudo pkill -f $D
        rm -r "$F"
        echo "manage_my_process stopped"

elif [ "$1" = restart ]
then
        sudo pkill -f $D
        rm -r "$F"
        ./$D &
        echo "echo $!" > $F
        echo "manage_my_process restarted"

else echo "Usage: manage_my_process {start|stop|restart}"
fi
